### ISSUE TITLE
Implement operations for ordered-float

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [reem/rust-ordered-float#11]
Hi,

I'm wondering if it would be beneficial to implement the operations of float for this structs. It is cumbersome to always write `NotNaN::unchecked_new(*self + *other)` etc.

Best regards

**Comment by Blei** [comment]
Seconded, same for NotNaN. Only a subset of operations would be available, but that's probably good enough.

**Comment by reem** [comment]
This is done now!
