### ISSUE TITLE
Changelog or a clear list of breaking changes between releases?

### ISSUE THREAD

**Issue by pacak** [reem/rust-ordered-float#140]
1. I'm trying to update our codebase to the next release, code fails to compile. Usually it's a quick look at the changelog or release merge request, but neither seems to be available. Would be great to have this.

2. Breaking change was introduced in #138 which requires to add a new constraint. Adding constraints is not a problem, but to add it I have to add a new dependency - `num-traits` which must be the same version (within cargo compatible versions) as `ordered-float` uses. This would break as soon as `num-traits` releases a new major version, usual approach is to reexport such traits  so constraints can look like this instead:

```rust
fn problem<T>(inputs: &mut [OrderedFloat<T>])
where
    T: ordered_float::FloatCore,
{
    inputs.sort();
}
```

**Comment by mbrubeck** [comment]
There is a changelog here: https://github.com/reem/rust-ordered-float/releases

I should add a link to the README and docs to make it more discoverable.
