### ISSUE TITLE
Missing binary op implementations for `OrderedFloat`

### ISSUE THREAD

**Issue by indietyp** [reem/rust-ordered-float#145]
Unlike the standard library or `NotNan`. `OrderedFloat` does not implement `impl<'a, T> Add<&'a OrderedFloat<T>> for &'a OrderedFloat<T>`, the same goes for `Div` and others.

Would it be possible add these implementations?

Thank you so much for the great library!

**Comment by mbrubeck** [comment]
Unfortunately, adding these impls triggered some weird type inference error/bug:

https://github.com/reem/rust-ordered-float/issues/91

**Comment by indietyp** [comment]
That's too bad! Thank you for the quick reply.

Although I wonder how the std is able to provide them 🤔
