### ISSUE TITLE
Debug implementation shouldn't display the `NotNan` wrapper

### ISSUE THREAD

**Issue by Ten0** [reem/rust-ordered-float#152]
Currently the debug implementation of `NotNan` is:
```
        Struct {
            f1: NotNan(
                18.25409836065574,
            ),
            f2: NotNan(
                0.11689901383196721,
            ),
        },
```

This seems unnecessarily verbose: when debugging structs that contain NotNan floats, we are probably interested by the values, without being particularly interested by being reminded at every step that they can't be `NaN` (I mean, we see that they are not `NaN` in their values anyway).

I would much prefer to read:

```
        Struct {
            f1: 18.25409836065574,
            f2: 0.11689901383196721,
        },
```

=> It would be useful to have the `Debug` implementation directly delegate to the inner float, instead of just being a `#[derive(Debug)]`.

Is that something that sounds ok? (I can PR this.)

**Comment by mbrubeck** [comment]
Yes, a patch for this would be welcome.
