### ISSUE TITLE
Feature request: Implement num_traits traits

### ISSUE THREAD

**Issue by Moredread** [reem/rust-ordered-float#16]
Do you think it'd be a good idea to implement the num_traits traits for this crate's types?

**Comment by ChristianBeilschmidt** [comment]
Yes, I think it would be good to have this additional set of operations: http://rust-num.github.io/num/num_traits/float/trait.Float.html

**Comment by lyro** [comment]
Actually it's not only this. In one of my projects I have generic code that has type bounds like `F: Num + Ord` (I just want to have a fully ordered number), but `Num` (from `num_traits`) is not implemented for `NotNaN` so it cannot be used easily. In fact, I do not know how to solve the problem but by defining a newtype around `NotNaN` and implementing the traits from `num_traits` on my own ...

**Comment by ChristianBeilschmidt** [comment]
Then why not commit the implementation and provide a pull request?

**Comment by mbrubeck** [comment]
This is now fixed on master.
