### ISSUE TITLE
NotNaN binary operations can create NaNs

### ISSUE THREAD

**Issue by ExpHP** [reem/rust-ordered-float#17]
NotNaN's implementation prevents binary operators from receiving a NaN operand, but this is far from the only way that a NaN may arise;

NaN, the menace that it is, is something that *all numeric binary operations* are capable of producing!

```rust
fn main() {
    let zero = NotNaN::new(0.).unwrap();
    let infinity = NotNaN::new(1./0.).unwrap();
    println!("{:?}", infinity + (-infinity)); // ==> NotNaN(NaN)
    println!("{:?}", infinity - infinity);    // ==> NotNaN(NaN)
    println!("{:?}", zero * infinity);        // ==> NotNaN(NaN)
    println!("{:?}", zero / zero);            // ==> NotNaN(NaN)
    println!("{:?}", zero % zero);            // ==> NotNaN(NaN)
}
```
Notice that due to unsafe optimizations in NotNaN, this enables undefined behavior in safe code.

**Comment by ExpHP** [comment]
cc @ChristianBeilschmidt who implemented the ops

**Comment by reem** [comment]
Argh! I guess we should add checks for producing NaN and panic if we've done so.
