### ISSUE TITLE
Add `TryFrom`, when stable

### ISSUE THREAD

**Issue by Lucretiel** [reem/rust-ordered-float#56]
Add an implementation of `TryFrom` for `NotNaN`, once `TryFrom` is stable (https://github.com/rust-lang/rust/issues/33417)

**Comment by Lucretiel** [comment]
This will probably require us to remove the `From` implementation, since Rust provides a blanket `impl<T, U: From<T>> TryFrom<T> for U`. We should probably do this anyway, as a matter of best practice (#57)

**Comment by hellow554** [comment]
It's stable btw ;)
