### ISSUE TITLE
Add Add trait implementation to OrderedFloat?

### ISSUE THREAD

**Issue by tiby312** [reem/rust-ordered-float#62]
This way you could pass an ordered float to a generic function that requires Add+Ord. Same question for Sub/Mul/Div.

**Comment by tiby312** [comment]
If I have a computation heavy generic math function that requires Ord, I would rather pass it an OrderedFloat instead of a NotNan since NotNan adds overhead to each computation, unlike OrderedFloat which only incurrs overhead on comparisons.

**Comment by martinellison** [comment]
The `pathfinding` crate requires at least `num_traits::identities::Zero` and `OrderedFloat` does not implement this. Actually, there are several more traits in `num_traits` that might be useful to someone.
