### ISSUE TITLE
Yank version with "*" deps

### ISSUE THREAD

**Issue by kornelski** [reem/rust-ordered-float#64]
An old version of `ordered-float` has dependencies specified with `"*"` version requirement (`stainless = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `ordered-float` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.1
```

**Comment by mbrubeck** [comment]
I have yanked ordered-float 0.0.1 and 0.0.2, which I believe are the only versions with wildcard dependencies.
