### ISSUE TITLE
Re-export `Float` trait

### ISSUE THREAD

**Issue by demurgos** [reem/rust-ordered-float#79]
I wanted to write a struct containing an `OrderedFloat`, but to implement various traits such as `Eq` or `Ord`, I need to use the `Float` trait bound but this trait is defined in `num-traits` instead of `OrderedFloat`.

The current situation forces me to add `num-traits` to my dependencies only to pull the `Float` trait. It would be nicer if the traits used by `OrderedFloat` were re-exported.

An important benefit to this is that it ensures that its the correct version of the trait in case there are multiple versions of `num-traits` in the dependency tree.

**Comment by mbrubeck** [comment]
Thanks for the suggestion! This is now implemented in `ordered-float` 2.2.0.
