### ISSUE TITLE
Use std::mem::transmute instead of raw pointer conversion

### ISSUE THREAD

**Issue by qiujiangkun** [reem/rust-ordered-float#80]
https://github.com/reem/rust-ordered-float/blob/eb30b6d4727f63b4e3d593193d35c1bd3deacf9a/src/lib.rs#L68
https://github.com/reem/rust-ordered-float/blob/eb30b6d4727f63b4e3d593193d35c1bd3deacf9a/src/lib.rs#L77
These can be done more explicitly with `unsafe { transmute(t) }`

**Comment by mbrubeck** [comment]
Personally I agree that `transmute` is a perfectly good way to do this, but it's worth noting that the transmute docs [specifically recommend](https://doc.rust-lang.org/std/mem/fn.transmute.html#alternatives) using pointer casts instead.

I don't think it makes a significant difference either way, so I'm just going to leave this as-is for now.
