### ISSUE TITLE
Rename 'unchecked_new' to 'new_unchecked'

### ISSUE THREAD

**Issue by Lemmih** [reem/rust-ordered-float#85]
`new_unchecked` appears to be the standard word order. A bit of searching show only three crates that use `unchecked_new`: `ordered-float`, `noisy_float`, and `tidb_query_datatype`. The standard libraries prefer `new_unchecked` and most other crates follow this convention.

Would you be interested in a PR that marks `unchecked_new` as deprecated and adds `new_unchecked`?

**Comment by mbrubeck** [comment]
> Would you be interested in a PR that marks `unchecked_new` as deprecated and adds `new_unchecked`?

Yes, please!

**Comment by mbrubeck** [comment]
Fixed by #86.
