### ISSUE TITLE
Crates version does not compile

### ISSUE THREAD

**Issue by OfficialURL** [reem/rust-ordered-float#95]
Creating an empty project with the `ordered-float = "2.7"` dependency does not compile. This is because of some `T::ONE` and `T::ZERO` calls that should have instead been `T::one()` and `T::zero()`. The version on GitHub does not have this issue.

**Comment by CryZe** [comment]
The crates.io version seems to be identical to the latest commit on master: https://docs.rs/ordered-float/2.7.0/src/ordered_float/lib.rs.html#454-464

**Comment by mbrubeck** [comment]
> Creating an empty project with the `ordered-float = "2.7"` dependency does not compile.

I could not reproduce this problem.  Can you provide more details?  What platform are you using, and what version of rustc?

> This is because of some `T::ONE` and `T::ZERO` calls that should have instead been `T::one()` and `T::zero()`.

This crate has never used `T::ONE` or `T::ZERO`.

**Comment by OfficialURL** [comment]
I apologize, it seems like I must have had corrupted my local copy of the library.
